"""initial schema with server defaults

Revision ID: 6bcb512607f6
Revises: 
Create Date: 2026-09-21 13:10:56.119381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types (AutoString) into autogenerated
# migrations but does not add the import. Without this line every
# generated script fails with NameError on first upgrade.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bcb512607f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('access_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('access_id')
    )
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_log_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_log_target_id'), ['target_id'], unique=False)

    op.create_table('accounts',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('ifsc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_customer_id'), ['customer_id'], unique=False)

    op.create_table('agents',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'agent'"), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('branches',
    sa.Column('ifsc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ifsc')
    )
    op.create_table('calls',
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'browser'"), nullable=False),
    sa.Column('final_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recording_consent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notice_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_final_state'), ['final_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_started_at'), ['started_at'], unique=False)

    op.create_table('cards',
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('daily_limit', sa.Float(), server_default=sa.text('(50000)'), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_customer_id'), ['customer_id'], unique=False)

    op.create_table('cases',
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('intake', sa.Text(), nullable=True),
    sa.Column('assigned_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('cheques',
    sa.Column('cheque_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('presented_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('cheque_number')
    )
    with op.batch_alter_table('cheques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cheques_account_id'), ['account_id'], unique=False)

    op.create_table('consents',
    sa.Column('consent_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('granted_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('withdrawn_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recording', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('consent_ref')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_session_id'), ['session_id'], unique=False)

    op.create_table('customers',
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enrolled', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_created_at'), ['created_at'], unique=False)

    op.create_table('handovers',
    sa.Column('handover_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('packet', sa.Text(), nullable=False),
    sa.Column('claimed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'queued'"), nullable=False),
    sa.PrimaryKeyConstraint('handover_id')
    )
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handovers_trace_id'), ['trace_id'], unique=False)

    op.create_table('holdings',
    sa.Column('holding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('as_of', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('holding_id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_customer_id'), ['customer_id'], unique=False)

    op.create_table('ledger',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('ts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sig', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_record_id'), ['record_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledger_session_id'), ['session_id'], unique=False)

    op.create_table('ledger_checkpoint',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('payees',
    sa.Column('payee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ifsc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('payee_id')
    )
    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payees_customer_id'), ['customer_id'], unique=False)

    op.create_table('recordings',
    sa.Column('recording_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retention_until', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purged_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('recording_id')
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordings_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_retention_until'), ['retention_until'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_clip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier_floor', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('clean_turns', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('verified_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_score', sa.Float(), nullable=True),
    sa.Column('verified_spoof', sa.Float(), nullable=True),
    sa.Column('verified_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_turns', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('turn_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('withdrawn_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_call_id'), ['call_id'], unique=False)

    op.create_table('sips',
    sa.Column('sip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fund', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('started_on', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'active'"), nullable=False),
    sa.PrimaryKeyConstraint('sip_id')
    )
    with op.batch_alter_table('sips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sips_customer_id'), ['customer_id'], unique=False)

    op.create_table('speakers',
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('n_clips', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enrolled_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('traces',
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traces_session_id'), ['session_id'], unique=False)

    op.create_table('transactions',
    sa.Column('txn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('txn_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_txn_account_ts', ['account_id', sa.literal_column('ts DESC')], unique=False)

    op.create_table('turns',
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interrupted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('call_id', 'turn_id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_trace_id'), ['trace_id'], unique=False)

    op.create_table('vault',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pii_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'token')
    )
    op.create_table('voice_enrollments',
    sa.Column('enrollment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_clips', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'live'"), nullable=False),
    sa.Column('consent_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_consent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    with op.batch_alter_table('voice_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_enrollments_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_enrollments_customer_id'))

    op.drop_table('voice_enrollments')
    op.drop_table('vault')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_trace_id'))
        batch_op.drop_index(batch_op.f('ix_turns_decision'))

    op.drop_table('turns')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_account_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_session_id'))

    op.drop_table('traces')
    op.drop_table('speakers')
    with op.batch_alter_table('sips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sips_customer_id'))

    op.drop_table('sips')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_call_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordings_retention_until'))
        batch_op.drop_index(batch_op.f('ix_recordings_call_id'))

    op.drop_table('recordings')
    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payees_customer_id'))

    op.drop_table('payees')
    op.drop_table('ledger_checkpoint')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_session_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_record_id'))

    op.drop_table('ledger')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_customer_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handovers_trace_id'))

    op.drop_table('handovers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_created_at'))

    op.drop_table('customers')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_session_id'))

    op.drop_table('consents')
    with op.batch_alter_table('cheques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheques_account_id'))

    op.drop_table('cheques')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cases_call_id'))

    op.drop_table('cases')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_customer_id'))

    op.drop_table('cards')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_started_at'))
        batch_op.drop_index(batch_op.f('ix_calls_final_state'))
        batch_op.drop_index(batch_op.f('ix_calls_customer_id'))

    op.drop_table('calls')
    op.drop_table('branches')
    op.drop_table('agents')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_customer_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_access_log_at'))
        batch_op.drop_index(batch_op.f('ix_access_log_actor'))

    op.drop_table('access_log')
    # ### end Alembic commands ###
