"""turn search columns

Revision ID: b1af5c5a864f
Revises: 6bcb512607f6
Create Date: 2026-09-21 13:44:54.917122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel renders its own column types (AutoString) into autogenerated
# migrations but does not add the import. Without this line every
# generated script fails with NameError on first upgrade.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1af5c5a864f'
down_revision: Union[str, Sequence[str], None] = '6bcb512607f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_tier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_turns_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_risk_tier'), ['risk_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_risk_tier'))
        batch_op.drop_index(batch_op.f('ix_turns_language'))
        batch_op.drop_column('language')
        batch_op.drop_column('intent')
        batch_op.drop_column('risk_tier')

    # ### end Alembic commands ###
