import React, { useEffect, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, NavLink, Navigate, Route, Routes } from 'react-router-dom'
import Customer from './routes/Customer'
import Compliance from './routes/Compliance'
import Record from './routes/Record'
import Agent from './routes/Agent'
import './styles.css'

// What this build of the frontend needs the backend to support. If the
// backend is older, say so loudly instead of letting the user discover it
// as a 405 on a button that obviously exists.
const NEEDS = ['customers.register', 'session.identify', 'compliance.search',
               'call.state', 'escalation.cases']

// Three different states, and the first version of this reported all of
// them as "the backend is running older code", including the one where the
// backend was simply still starting. That was worse than no banner: it sent
// you to restart the very thing that was mid start.
type BackendState =
  | { kind: 'ok' }
  | { kind: 'starting' }
  | { kind: 'stale'; missing: string[] }
  | { kind: 'warming'; detail: string }

function StaleBackendBanner() {
  const [state, setState] = useState<BackendState>({ kind: 'starting' })

  useEffect(() => {
    let alive = true
    const check = async () => {
      try {
        const res = await fetch('/api/health')
        if (!res.ok) throw new Error(String(res.status))
        const h = await res.json()
        const missing = NEEDS.filter((n) => !(h.features || []).includes(n))
        if (!alive) return
        if (missing.length) setState({ kind: 'stale', missing })
        else if (h.warmup?.state === 'pending')
          setState({ kind: 'warming', detail: 'the first reply will be slower' })
        else setState({ kind: 'ok' })
      } catch {
        // Not up yet, or not up any more. Either way, keep looking: a
        // cold start takes a few seconds and the banner should clear
        // itself rather than making you reload the page.
        if (alive) setState({ kind: 'starting' })
      }
    }
    check()
    const t = setInterval(check, 2000)
    return () => { alive = false; clearInterval(t) }
  }, [])

  if (state.kind === 'ok') return null
  const amber = { background: '#fff7e6', color: '#7a4a00' }
  const red = { background: '#fdecea', color: '#8a1c11' }

  if (state.kind === 'starting') return (
    <div className="banner" style={amber} data-testid="backend-starting">
      Waiting for the backend on port 8000. It loads speech models on the way
      up, so the first few seconds are normal. This clears itself.
    </div>
  )
  if (state.kind === 'warming') return (
    <div className="banner" style={amber} data-testid="backend-warming">
      The backend is up and answering. It is still pre-synthesising the fixed
      prompts, so {state.detail}.
    </div>
  )
  return (
    <div className="banner" style={red} data-testid="stale-backend">
      The backend is running older code than this page: it is missing{' '}
      <strong>{state.missing.join(', ')}</strong>. Restart it with{' '}
      <code>make demo</code>. Until you do, buttons that exist here will fail
      with 404 or 405.
    </div>
  )
}

function Shell() {
  return (
    <>
      <StaleBackendBanner />
      <div className="banner">
        SYNTHETIC DATA ONLY. Every customer, account, card, transaction and enrolled voice in
        this system is generated by a seed script. No real personal data is present, and no
        real banking system is connected.
      </div>
      <header className="top">
        <h1>Compliance-Aware Multilingual Voice Assistant for BFSI</h1>
        <nav>
          <NavLink to="/" end className={({ isActive }) => (isActive ? 'active' : '')}>Customer console</NavLink>
          <NavLink to="/compliance" className={({ isActive }) => (isActive ? 'active' : '')}>Compliance dashboard</NavLink>
          <NavLink to="/agent" className={({ isActive }) => (isActive ? 'active' : '')}>Agent console</NavLink>
          <NavLink to="/record" className={({ isActive }) => (isActive ? 'active' : '')}>Record eval set</NavLink>
        </nav>
      </header>
      <Routes>
        <Route path="/" element={<Customer />} />
        <Route path="/compliance" element={<Compliance />} />
        <Route path="/agent" element={<Agent />} />
        <Route path="/record" element={<Record />} />
        <Route path="*" element={<Navigate to="/" />} />
      </Routes>
    </>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter><Shell /></BrowserRouter>
  </React.StrictMode>,
)
