"""FastAPI entrypoint and WebSocket session handler.

Every endpoint except /capabilities and /health requires a JWT. The role
matrix lives in security/rbac.py and tests/test_rbac.py walks every cell of it,
including the one that matters most: a customer token must not be able to read
the compliance export.
"""
from __future__ import annotations

import asyncio
import json
import os
import time
from contextlib import asynccontextmanager
from typing import Annotated, Any

from fastapi import (Depends, FastAPI, File, Form, HTTPException, UploadFile,
                     WebSocket, WebSocketDisconnect)
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel

from . import db, turn
from .capabilities import registry_dict
from .config import DB_PATH, LANGUAGES, ROLES
from .security import ledger, rbac
from .trace import utcnow

STARTED_AT = time.time()
CONN = None
METRICS: dict[str, Any] = {"turns": 0, "decisions": {}, "stage_ms": {}, "errors": 0}


def _warm_models() -> None:
    """Load the lazy models at startup rather than inside the first turn.

    Without this the first live turn pays about 3.5 seconds to load the
    embedding model, which on stage looks like the system hanging. Failures
    here are logged and ignored: a missing model must not stop the server from
    booting, because the text path and the ledger still work without it.
    """
    for name, load in (("embeddings", lambda: __import__(
            "app.pipeline.embed", fromlist=["embed"]).get_model()),):
        try:
            t0 = time.perf_counter()
            load()
            print(f"warmed {name} in {time.perf_counter() - t0:.1f}s", flush=True)
        except Exception as exc:                          # noqa: BLE001
            print(f"could not warm {name}: {exc}", flush=True)


@asynccontextmanager
async def lifespan(app: FastAPI):
    global CONN
    CONN = db.init_db(DB_PATH)
    if os.environ.get("BFSI_SKIP_WARMUP") != "1":
        await asyncio.to_thread(_warm_models)
    yield
    if CONN:
        CONN.close()


app = FastAPI(title="Compliance-Aware Multilingual Voice Assistant for BFSI",
              version="0.1.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"],
                   allow_headers=["*"])


def conn():
    if CONN is None:
        raise HTTPException(503, "database not ready")
    return CONN


# ---------------------------------------------------------------- models

class ConsentRequest(BaseModel):
    customer_id: str | None = None
    device_id: str | None = None
    voice_clip: str | None = None
    languages: str = ",".join(LANGUAGES)
    accepted: bool = True


class TextTurnRequest(BaseModel):
    session_id: str
    text: str | None = None
    otp: str | None = None
    confirm: bool | None = None
    asr_confidence: float | None = None


class TokenRequest(BaseModel):
    subject: str
    role: str


# ---------------------------------------------------------------- open endpoints

@app.get("/health")
def health():
    return {"ok": True, "uptime_s": round(time.time() - STARTED_AT, 1)}


@app.get("/capabilities")
def capabilities():
    """The honesty registry. Deliberately unauthenticated: anybody looking at
    this system should be able to see what is real in it without a token."""
    return {"capabilities": registry_dict(),
            "legend": {
                "REAL": "a genuine implementation of the component named",
                "BASELINE": "real but deliberately simpler than the paper's target",
                "SIMULATED": "not implemented, stands in for an external system"},
            "synthetic_data_notice": (
                "All customers, accounts, cards, transactions and enrolled voices in "
                "this system are synthetic and generated by a seed script. No real "
                "personal data is present.")}


@app.post("/auth/demo-token")
def demo_token(req: TokenRequest):
    """Demo-only token issuer. There is no identity provider in this build, and
    the capability registry records that RBAC is demo-scale."""
    if req.role not in ROLES:
        raise HTTPException(400, f"role must be one of {ROLES}")
    return {"token": rbac.issue_token(req.subject, req.role), "role": req.role,
            "note": "demo issuer, no identity provider; production design names Keycloak"}


# ---------------------------------------------------------------- session

@app.post("/session/consent")
def create_consent(req: ConsentRequest,
                   principal: Annotated[dict, Depends(rbac.require("session:create"))]):
    if not req.accepted:
        raise HTTPException(400, "consent is required before a session can open")
    out = turn.create_session(conn(), req.customer_id, req.device_id,
                              req.voice_clip, req.languages)
    return out


@app.post("/session/{session_id}/withdraw")
def withdraw(session_id: str,
             principal: Annotated[dict, Depends(rbac.require("consent:withdraw"))]):
    try:
        return turn.withdraw_consent(conn(), session_id)
    except KeyError as exc:
        raise HTTPException(404, str(exc))


@app.get("/session/{session_id}/traces")
def session_traces(session_id: str,
                   principal: Annotated[dict, Depends(rbac.require("trace:read_own"))]):
    rows = conn().execute(
        "SELECT body FROM traces WHERE session_id=? ORDER BY turn_index", (session_id,))
    return {"session_id": session_id, "traces": [json.loads(r["body"]) for r in rows]}


# ---------------------------------------------------------------- turns

def _record_metrics(t) -> None:
    METRICS["turns"] += 1
    key = t.decision or "unknown"
    METRICS["decisions"][key] = METRICS["decisions"].get(key, 0) + 1
    for stage in t.stages:
        METRICS["stage_ms"].setdefault(stage.stage, []).append(stage.duration_ms)


@app.post("/turn/text")
def text_turn(req: TextTurnRequest,
              principal: Annotated[dict, Depends(rbac.require("turn:submit"))]):
    """The text fallback. Everything after the transcript is identical to the
    voice path, which is what makes the demo survive a dead microphone."""
    try:
        t = turn.run_turn(conn(), req.session_id, text=req.text, otp=req.otp,
                          confirm=req.confirm, asr_confidence=req.asr_confidence)
    except KeyError as exc:
        raise HTTPException(404, str(exc))
    except PermissionError as exc:
        raise HTTPException(403, str(exc))
    _record_metrics(t)
    return t.model_dump(mode="json")


@app.post("/turn/audio")
async def audio_turn(session_id: Annotated[str, Form()],
                     audio: Annotated[UploadFile, File()],
                     principal: Annotated[dict, Depends(rbac.require("turn:submit"))]):
    data = await audio.read()
    try:
        t = await asyncio.to_thread(turn.run_turn, conn(), session_id, audio=data)
    except KeyError as exc:
        raise HTTPException(404, str(exc))
    del data                       # the buffer is dropped as soon as the turn is done
    _record_metrics(t)
    return t.model_dump(mode="json")


@app.get("/trace/{trace_id}")
def get_trace(trace_id: str,
              principal: Annotated[dict, Depends(rbac.require("trace:read_own"))]):
    row = conn().execute("SELECT body FROM traces WHERE trace_id=?", (trace_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"no trace {trace_id}")
    return json.loads(row["body"])


# ---------------------------------------------------------------- speech out

@app.get("/tts")
def speak(text: str, language: str = "en",
          principal: Annotated[dict, Depends(rbac.require("turn:submit"))] = None):
    from .pipeline import tts
    out = tts.synthesize(text, language)
    if not out["available"]:
        raise HTTPException(503, out["error"])
    return Response(content=out["audio"], media_type="audio/wav",
                    headers={"X-Piper-Voice": out["voice"]})


# ---------------------------------------------------------------- enrolment

@app.post("/enroll")
async def enroll(customer_id: Annotated[str, Form()],
                 clips: Annotated[list[UploadFile], File()],
                 principal: Annotated[dict, Depends(rbac.require("enroll"))]):
    from .security import speaker
    if len(clips) < 3:
        raise HTTPException(400, "three enrolment clips are required")
    data = [await c.read() for c in clips]
    out = await asyncio.to_thread(speaker.enrol, conn(), customer_id, data, "live")
    ledger.append(conn(), "enrolment",
                  {"customer_ref": customer_id, "n_clips": len(data), "source": "live",
                   "mean_pairwise_cosine": out["mean_pairwise_cosine"]})
    return out


@app.post("/verify")
async def verify_voice(session_id: Annotated[str, Form()],
                       audio: Annotated[UploadFile, File()],
                       principal: Annotated[dict, Depends(rbac.require("turn:submit"))]):
    """Run a live voice check for this session.

    This is the only thing that authenticates a caller. A turn carries the
    result for a few minutes and a few turns, then it expires and the caller
    is asked again.
    """
    data = await audio.read()
    try:
        out = await asyncio.to_thread(turn.record_verification, conn(), session_id, data)
    except KeyError as exc:
        raise HTTPException(404, str(exc))
    del data
    return out


@app.post("/verify/demo")
def verify_demo(session_id: Annotated[str, Form()],
                principal: Annotated[dict, Depends(rbac.require("turn:submit"))]):
    """Dead-microphone fallback: run the check against the seeded clip attached
    to the session. Recorded as SIMULATED in the trace and in the ledger,
    because it demonstrates the mechanism rather than checking a speaker."""
    try:
        return turn.record_verification(conn(), session_id, None, source="demo_clip")
    except KeyError as exc:
        raise HTTPException(404, str(exc))


# ---------------------------------------------------------------- ledger

@app.post("/ledger/verify")
def ledger_verify(use_checkpoints: bool = True,
                  principal: Annotated[dict, Depends(rbac.require("ledger:verify"))] = None):
    t0 = time.perf_counter()
    out = ledger.verify(conn(), use_checkpoints=use_checkpoints)
    out["elapsed_ms"] = round((time.perf_counter() - t0) * 1000, 3)
    out["verified_at"] = utcnow().isoformat()
    return out


@app.get("/ledger/export")
def ledger_export(principal: Annotated[dict, Depends(rbac.require("ledger:export"))]):
    """Compliance export: the full chain plus a detached HMAC signature."""
    out = ledger.export(conn())
    out["exported_by"] = principal.get("sub")
    return JSONResponse(out, headers={"Content-Disposition":
                                      'attachment; filename="ledger-export.json"'})


@app.get("/ledger/records")
def ledger_records(limit: int = 200, offset: int = 0,
                   principal: Annotated[dict, Depends(rbac.require("ledger:verify"))] = None):
    rows = conn().execute(
        "SELECT idx, record_id, kind, session_id, ts, prev_hash, hash, sig, payload"
        " FROM ledger ORDER BY idx DESC LIMIT ? OFFSET ?", (limit, offset))
    total = conn().execute("SELECT COUNT(*) c FROM ledger").fetchone()["c"]
    return {"total": total, "records": [dict(r) for r in rows]}


# ---------------------------------------------------------------- escalation

@app.get("/handovers")
def handovers(principal: Annotated[dict, Depends(rbac.require("handover:read"))]):
    rows = conn().execute(
        "SELECT handover_id, trace_id, session_id, created_at, reason, status, claimed_by"
        " FROM handovers ORDER BY created_at DESC LIMIT 50")
    return {"handovers": [dict(r) for r in rows]}


@app.post("/agent/handover/{trace_id}")
def claim_handover(trace_id: str,
                   principal: Annotated[dict, Depends(rbac.require("handover:claim"))]):
    row = conn().execute("SELECT * FROM handovers WHERE trace_id=?", (trace_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"no handover for trace {trace_id}")
    agent = principal.get("sub")
    conn().execute("UPDATE handovers SET claimed_by=?, status='claimed' WHERE handover_id=?",
                   (agent, row["handover_id"]))
    conn().commit()
    ledger.append(conn(), "handover_claimed",
                  {"handover_id": row["handover_id"], "trace_id": trace_id, "agent_id": agent},
                  session_id=row["session_id"])
    return {"handover_id": row["handover_id"], "agent_id": agent,
            "packet": json.loads(row["packet"])}


# ---------------------------------------------------------------- observability

@app.get("/metrics")
def metrics(principal: Annotated[dict, Depends(rbac.require("metrics:read"))]):
    """Latency percentiles per stage and decision counters, read off the traces
    rather than a separate metrics pipeline. Prometheus and Grafana are the
    production substitution, recorded in STACK_MAPPING.md."""
    import statistics
    stages = {}
    for name, samples in METRICS["stage_ms"].items():
        ordered = sorted(samples)
        stages[name] = {
            "n": len(ordered),
            "p50_ms": round(statistics.median(ordered), 2),
            "p95_ms": round(ordered[min(len(ordered) - 1, int(0.95 * len(ordered)))], 2),
            "mean_ms": round(statistics.fmean(ordered), 2)}
    counts = dict(conn().execute(
        "SELECT kind, COUNT(*) FROM ledger GROUP BY kind").fetchall()) if CONN else {}
    return {"turns": METRICS["turns"], "decisions": METRICS["decisions"],
            "stages": stages, "ledger_records_by_kind": counts,
            "uptime_s": round(time.time() - STARTED_AT, 1)}


@app.get("/kb")
def kb_documents(principal: Annotated[dict, Depends(rbac.require("trace:read_own"))]):
    """The policy KB as the dashboard shows it, including superseded versions."""
    from .pipeline import retrieval
    try:
        _, chunks = retrieval._index()
    except RuntimeError as exc:
        raise HTTPException(503, str(exc))
    docs: dict[str, dict] = {}
    for c in chunks:
        key = f"{c['doc_id']}@{c['version']}"
        d = docs.setdefault(key, {"doc_id": c["doc_id"], "version": c["version"],
                                  "title": c["title"], "category": c["category"],
                                  "effective_date": c["effective_date"],
                                  "superseded_by": c["superseded_by"], "sections": []})
        d["sections"].append(c["section"])
    return {"documents": sorted(docs.values(), key=lambda d: (d["doc_id"], d["version"]))}


# ---------------------------------------------------------------- websocket

@app.websocket("/ws/session")
async def ws_session(ws: WebSocket):
    """Audio in, partial transcript and reply out.

    Protocol, deliberately small:
      client -> {"type": "start", "token": "...", "session_id": "..."}
      client -> binary audio frames (16 kHz int16 PCM)
      client -> {"type": "end"}          finalise the utterance and run the turn
      client -> {"type": "text", ...}    the fallback path over the same socket
      server -> {"type": "partial"|"trace"|"reply"|"error", ...}
    """
    await ws.accept()
    buffer = bytearray()
    session_id: str | None = None
    principal: dict | None = None
    try:
        while True:
            message = await ws.receive()
            if "bytes" in message and message["bytes"] is not None:
                buffer.extend(message["bytes"])
                if len(buffer) % (32000 * 2) < 4096:        # roughly every 2 seconds
                    await ws.send_json({"type": "partial",
                                        "buffered_s": round(len(buffer) / 32000, 2)})
                continue
            if "text" not in message or message["text"] is None:
                break
            msg = json.loads(message["text"])
            kind = msg.get("type")

            if kind == "start":
                try:
                    principal = rbac.decode_token(msg.get("token", ""))
                except HTTPException as exc:
                    await ws.send_json({"type": "error", "error": exc.detail})
                    await ws.close()
                    return
                if not rbac.allowed(principal.get("role", ""), "turn:submit"):
                    await ws.send_json({"type": "error", "error": "role may not submit turns"})
                    await ws.close()
                    return
                session_id = msg.get("session_id")
                buffer.clear()
                await ws.send_json({"type": "ready", "session_id": session_id})

            elif kind in ("end", "text"):
                if not principal or not session_id:
                    await ws.send_json({"type": "error", "error": "send start first"})
                    continue
                audio = bytes(buffer) if kind == "end" and buffer else None
                buffer.clear()
                try:
                    t = await asyncio.to_thread(
                        turn.run_turn, conn(), session_id,
                        text=msg.get("text"), audio=audio, otp=msg.get("otp"),
                        confirm=msg.get("confirm"))
                except Exception as exc:                     # noqa: BLE001
                    METRICS["errors"] += 1
                    await ws.send_json({"type": "error", "error": str(exc)})
                    continue
                _record_metrics(t)
                await ws.send_json({"type": "trace", "trace": t.model_dump(mode="json")})
                if t.reply_text:
                    from .pipeline import tts
                    spoken = await asyncio.to_thread(tts.synthesize, t.reply_text,
                                                     t.reply_language)
                    await ws.send_json({"type": "reply", "text": t.reply_text,
                                        "language": t.reply_language,
                                        "voice": spoken["voice"],
                                        "audio_available": spoken["available"]})
                    if spoken["available"]:
                        await ws.send_bytes(spoken["audio"])

            elif kind == "close":
                break
    except WebSocketDisconnect:
        pass
    finally:
        buffer.clear()             # raw audio never outlives the connection
