import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, NavLink, Navigate, Route, Routes } from 'react-router-dom'
import Customer from './routes/Customer'
import Compliance from './routes/Compliance'
import './styles.css'

function Shell() {
  return (
    <>
      <div className="banner">
        SYNTHETIC DATA ONLY. Every customer, account, card, transaction and enrolled voice in
        this system is generated by a seed script. No real personal data is present, and no
        real banking system is connected.
      </div>
      <header className="top">
        <h1>Compliance-Aware Multilingual Voice Assistant for BFSI</h1>
        <nav>
          <NavLink to="/" end className={({ isActive }) => (isActive ? 'active' : '')}>Customer console</NavLink>
          <NavLink to="/compliance" className={({ isActive }) => (isActive ? 'active' : '')}>Compliance dashboard</NavLink>
        </nav>
      </header>
      <Routes>
        <Route path="/" element={<Customer />} />
        <Route path="/compliance" element={<Compliance />} />
        <Route path="*" element={<Navigate to="/" />} />
      </Routes>
    </>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter><Shell /></BrowserRouter>
  </React.StrictMode>,
)
